---
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-yaml
      - id: debug-statements
        language_version: python3

# ----- Code Formatting ------------------------------------------------------------------------->
  - repo: https://github.com/saltstack/pre-commit-remove-import-headers
    rev: 1.0.0
    hooks:
      - id: remove-import-headers

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.6+
        args: [--py36-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: []

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
# <---- Code Formatting --------------------------------------------------------------------------

# ----- Static Code Analysis -------------------------------------------------------------------->
  - repo: https://github.com/PyCQA/flake8/
    rev: 3.8.1
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [flake8-typing-imports==1.9.0]
# <---- Static Code Analysis ---------------------------------------------------------------------

# ----- Static Requirements --------------------------------------------------------------------->
  # ----- Testing Static Requirements ----------------------------------------------------------->
#  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
#    rev: master
#    hooks:
#      - id: pip-tools-compile
#        alias: compile-3.6-test-requirements
#        name: Py3.6 Test Requirements
#        files: ^requirements/(base\.txt|tests\.in)$
#        pass_filenames: false
#        args:
#          - -v
#          - --py-version=3.6
#          - --platform=linux
#          - requirements/tests.in
#
#  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
#    rev: master
#    hooks:
#      - id: pip-tools-compile
#        alias: compile-3.7-test-requirements
#        name: Py3.7 Test Requirements
#        files: ^requirements/(base\.txt|tests\.in)$
#        pass_filenames: false
#        args:
#          - -v
#          - --py-version=3.7
#          - --platform=linux
#          - requirements/tests.in
#
#  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
#    rev: master
#    hooks:
#      - id: pip-tools-compile
#        alias: compile-3.8-test-requirements
#        name: Py3.8 Test Requirements
#        files: ^requirements/(base\.txt|tests\.in)$
#        pass_filenames: false
#        args:
#          - -v
#          - --py-version=3.8
#          - --platform=linux
#          - requirements/tests.in
#
#  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
#    rev: master
#    hooks:
#      - id: pip-tools-compile
#        alias: compile-3.9-test-requirements
#        name: Py3.9 Test Requirements
#        files: ^requirements/(base\.txt|tests\.in)$
#        pass_filenames: false
#        args:
#          - -v
#          - --py-version=3.9
#          - --platform=linux
#          - requirements/tests.in
#
#  - repo: https://github.com/saltstack/pip-tools-compile-impersonate
#    rev: master
#    hooks:
#      - id: pip-tools-compile
#        alias: compile-3.10-test-requirements
#        name: Py3.10 Test Requirements
#        files: ^requirements/(base\.txt|tests\.in)$
#        pass_filenames: false
#        args:
#          - -v
#          - --py-version=3.10
#          - --platform=linux
#          - requirements/tests.in
  # <---- Testing Static Requirements ------------------------------------------------------------
# <---- Static Requirements ----------------------------------------------------------------------

# vim: colorcolumn=100
